
BID_TYPE = 0
ASK_TYPE = 1

#Command Types
NEW_ORDER          = 100
EDIT_ORDER         = 101
CANCEL_ORDER       = 102
GET_LAST_PRICE     = 103
RESPONSE           = 200

#Response Types
RESPONSE_ACK                       = 201
RESPONSE_ORDER_FULLY_MATCHED       = 202
RESPONSE_ORDER_PARTIALLY_MATCHED   = 203
RESPONSE_ORDER_CANCELLED           = 204
RESPONSE_ORDER_EDITED              = 205

#Order Match Types
ORDER_NOT_MATCHED       = 0
ORDER_PARTIALLY_MATCHED = 1
ORDER_FULLY_MATCHED     = 2